# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#about"
#   weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40


# [[main]]
#    name = "English Grammar"
#    url = "#"
#    identifier = "grammar"
#    weight = 10

# [[main]]
#    name = "English - Beginner level"
#    url = "english-beginner/"
#    parent = "grammar"
#    weight = 20

# [[main]]
#    name = "English - Intermediate level"
#    url = "english-intermediate/"
#    parent = "grammar"
#    weight = 22

[[main]]
   name = "English - Beginner"
   url = "english-beginner/"
   identifier = "grammar-beginner"
   weight = 10

   [[main]]
   name = "English - Introduction"
   url = "english-beginner/english-introduction/"
   parent = "grammar-beginner"
   weight = 11

   [[main]]
   name = "Structure of Sentence"
   url = "english-beginner/structure-of-sentence/"
   parent = "grammar-beginner"
   weight = 12

   [[main]]
   name = "Determiners"
   url = "english-beginner/determiners/"
   parent = "grammar-beginner"
   weight = 13



[[main]]
   name = "English - Intermediate"
   url = "english-intermediate/"
   identifier = "grammar-intermediate"
   weight = 20

   [[main]]
   name = "Nouns"
   url = "english-intermediate/nouns/"
   parent = "grammar-intermediate"
   weight = 21


[[main]]
   name = "Arithmetic"
   url = "#"
   identifier = "arithmetic"
   weight = 30

   [[main]]
   name = "Percentage"
   url = "arithmetic-beginner/percentage/"
   parent = "arithmetic"
   weight = 31

   [[main]]
   name = "Profit and Loss"
   url = "arithmetic-beginner/profit-and-loss/"
   parent = "arithmetic"
   weight = 32

   [[main]]
   name = "Interest"
   url = "arithmetic-beginner/interest/"
   parent = "arithmetic"
   weight = 33

   [[main]]
   name = "Ratio and Proportion"
   url = "arithmetic-beginner/ratio-and-proportion/"
   parent = "arithmetic"
   weight = 34

   [[main]]
   name = "Average, Mixtures & Alligation"
   url = "arithmetic-beginner/average-mixtures-alligation/"
   parent = "arithmetic"
   weight = 35

   [[main]]
   name = "Time, Speed & Distance"
   url = "arithmetic-beginner/time-speed-distance/"
   parent = "arithmetic"
   weight = 36

   [[main]]
   name = "Time & Work"
   url = "arithmetic-beginner/time-and-work/"
   parent = "arithmetic"
   weight = 37

   [[main]]
   name = "Number System"
   url = "arithmetic-beginner/number-system/"
   parent = "arithmetic"
   weight = 38

   [[main]]
   name = "Data Interpretation"
   url = "arithmetic-beginner/data-interpretation/"
   parent = "arithmetic"
   weight = 40


[[main]]
   name = "Higher Maths"
   url = "higher-maths/"
   identifier = "higher-maths"
   weight = 50

   [[main]]
   name = "Permutation & Combination"
   url = "higher-maths/permutation-and-combination/"
   parent = "higher-maths"
   weight = 51

   [[main]]
   name = "Probability"
   url = "higher-maths/probability/"
   parent = "higher-maths"
   weight = 52



[[main]]
   name = "Analytical Reasoning"
   url = "#"
   identifier = "analytical-reasoning"
   weight = 70

   [[main]]
   name = "Dice"
   url = "reasoning-beginner/dices/"
   parent = "analytical-reasoning"
   weight = 71

   [[main]]
   name = "Cubes"
   url = "reasoning-beginner/cubes/"
   parent = "analytical-reasoning"
   weight = 72

   [[main]]
   name = "Calendar"
   url = "reasoning-beginner/calendar/"
   parent = "analytical-reasoning"
   weight = 73

   [[main]]
   name = "Clocks"
   url = "reasoning-beginner/clocks/"
   parent = "analytical-reasoning"
   weight = 74

   [[main]]
   name = "Direction & Distance"
   url = "reasoning-beginner/direction-and-distance/"
   parent = "analytical-reasoning"
   weight = 75

   [[main]]
   name = "Syllogism"
   url = "reasoning-beginner/syllogism/"
   parent = "analytical-reasoning"
   weight = 76

   [[main]]
   name = "Blood Relations"
   url = "reasoning-beginner/blood-relations/"
   parent = "analytical-reasoning"
   weight = 77

   [[main]]
   name = "Venn Diagram"
   url = "reasoning-beginner/venn-diagram/"
   parent = "analytical-reasoning"
   weight = 78

   [[main]]
   name = "Puzzles"
   url = "reasoning-beginner/puzzles/"
   parent = "analytical-reasoning"
   weight = 80



[[main]]
   name = "Pattern Reasoning"
   url = "#"
   identifier = "pattern-reasoning"
   weight = 90

   [[main]]
   name = "Number & Alphabet Series"
   url = "reasoning-beginner/number-and-alphabet-series/"
   parent = "pattern-reasoning"
   weight = 91

   [[main]]
   name = "Coding-Decoding"
   url = "reasoning-beginner/coding-decoding/"
   parent = "pattern-reasoning"
   weight = 92


[[main]]
   name = "Contact"
   url = "#"
   identifier = "contact"
   weight = 360

   [[main]]
   name = "Contact Us"
   url = "#contact"
   parent = "contact"
   weight = 361

   [[main]]
   name = "About Us"
   url = "#about"
   parent = "contact"
   weight = 362


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
