# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# [[main]]
#   name = "Home"
#   url = "#about"
#   weight = 10

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40


[[main]]
   name = "English Grammar"
   url = "#"
   identifier = "grammar"
   weight = 10

[[main]]
   name = "English - Beginner level"
   url = "english-beginner/"
   parent = "grammar"
   weight = 20

[[main]]
   name = "English - Intermediate level"
   url = "english-intermediate/"
   parent = "grammar"
   weight = 22

[[main]]
   name = "Arithmetic"
   url = "#"
   identifier = "arithmetic"
   weight = 30

[[main]]
   name = "Arithmetic - Beginner level"
   url = "arithmetic-beginner/"
   parent = "arithmetic"
   weight = 40

[[main]]
   name = "Higher Maths"
   url = "higher-maths/"
   identifier = "maths"
   weight = 50

[[main]]
   name = "Reasoning"
   url = "#"
   identifier = "reasoning"
   weight = 150

[[main]]
   name = "Reasoning - Beginner level"
   url = "reasoning-beginner/"
   parent = "reasoning"
   weight = 160

[[main]]
  name = "About Us"
  url = "#about"
  weight = 350

[[main]]
  name = "Contact Us"
  url = "#contact"
  weight = 360

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
